name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}
author: khjxiaogu
depend: [PowerNBT]
commands:
  wskill:
    description: 武器技能插件指令
    permission: ${project.artifactId}.admin
    usage: /wskill
permissions:
  ${project.artifactId}.admin:
    description: 武器技能插件的权限
    default: op
